version: "3.9"
services:
  redis:
    image: redis:7
    ports: ["6379:6379"]
  qdrant:
    image: qdrant/qdrant:latest
    ports: ["6333:6333"]
    volumes: ["./infra/qdrant:/qdrant/storage"]
  orchestrator:
    build:
      context: .
      dockerfile: services/orchestrator/Dockerfile
    environment:
      - ENV_FILE=.env
    ports: ["8000:8000"]
    depends_on: [redis, qdrant]
  ops:
    build:
      context: .
      dockerfile: services/api/Dockerfile
    environment:
      - ENV_FILE=.env
      - REDIS_URL=redis://redis:6379/0
      - QDRANT_URL=http://qdrant:6333
    ports: ["9000:9000"]
    depends_on: [orchestrator]
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://127.0.0.1:9000/healthz"]
      interval: 5s
      timeout: 3s
      retries: 10
  swarm:
    build:
      context: .
      dockerfile: ai_swarm/Dockerfile
    environment:
      - ENV_FILE=.env
      - OPS_API_URL=http://ops:9000
      - SWARM_AUTOSUBMIT=false
      - SWARM_QUORUM=0.67
    ports: ["9100:9100"]
    depends_on: [ops]
  chain:
    image: trufflesuite/ganache:v7.9.2
    ports: ["8545:8545"]
    command: ["--wallet.totalAccounts=10", "--chain.vmErrorsOnRPCResponse=true"]
