site_name: Trustiva Docs
site_url: https://docs.trustiva.ai/
repo_url: https://github.com/Trustiva7777/Trustiva-Ai-
theme:
  name: material
  palette:
    - scheme: default
      primary: black
      accent: amber
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Trustiva7777/Trustiva-Ai-
  open_graph:
    image: assets/og-banner.svg
    type: website
    title: Trustiva AI + Proof Kernel
    description: Sovereign-grade AI-to-Blockchain Trust Infrastructure
nav:
  - Overview: index.md
  - Runbook: README_RUNBOOK.md
  - Appraisal: Trustiva_1.0_Appraisal.md
  - Playbook: playbook.md
  - Governance:
      - Security: governance/security.md
      - Contributing: governance/contributing.md
      - Changelog: governance/changelog.md